GH-114: Lock down bug tracker to developers only
php/web-bugs pull request #120
Opened 2024-07-20 11:11 UTC by cmb69

All further conversation about bugs is supposed to happen on Github. We still allow developers to edit the bug tracker, so they can clean up.

We start by disallowing users to add patches.

TODO:
* [ ] disallow commenting
* [ ] disallow adding PRs?
* more?
---

Note that I do not have a development for web-bugs, so this is completely untested. Maybe somebody with a development environment can check this? (and perhaps even help to solve further tasks)

2024-07-20 16:44 UTC, cmb69 commented
Note that I took (almost) no effort to clean up dead code (the whole CAPTCHA might not be needed anymore, and likely there is more dead code); that might be done later, or never be done at all.

Otherwise I think this PR is ready for review.

2024-07-20 16:55 UTC, php-pulls commented
Although I'm not necessarily against doing this, I don't think it is good practise to argue for doing this on just a PR.

2024-07-20 17:26 UTC, cmb69 commented
Fair point! I've sent a respective mail to [php-webmasters](https://news-web.php.net/php.webmaster/31847) and [internals](https://news-web.php.net/php.internals/124521).

2024-07-22 15:34 UTC, derickr commented
Heh, why does that show as `php-pulls`, and not as me. I wonder.

2024-07-22 15:53 UTC, cmb69 commented
Maybe your email address is associated with that user?

2024-07-29 12:28 UTC, derickr commented
I do. But I'm not back until later in the week.

2024-07-29 12:41 UTC, cmb69 commented
No need to hurry. Thank you!

2024-07-29 14:08 UTC, derickr commented
If we only had tests 🤣

2024-07-31 16:44 UTC, derickr commented
There are actually tests!

2024-07-31 16:45 UTC, derickr commented
I can't find any issues with this patch, but I am not sure if I have tested every path — could you perhaps list the ones, as there seem to be more than the four checkboxes.

2024-07-31 17:09 UTC, derickr requested changes
LGTM, except for the single comment.

2024-07-31 17:26 UTC, cmb69 reviewed
Some comments about what the changes are supposed to do.

2024-07-31 17:26 UTC, cmb69 commented on www/bug.php
> +if ($edit && $edit < 2) {
This disables querying the database if "add comment" is pressed.

2024-07-31 17:26 UTC, cmb69 commented on www/bug.php
> +        exit;
This catches requests to add a comment from users (these are no longer supposed to come via UI, but possibly direct HTTP requests).

2024-07-31 17:26 UTC, cmb69 commented on www/bug.php
> +            If you forgot your password, <a href="bug-pwd-finder.php?id=<?php echo $bug_id; ?>">you can retrieve your password here</a>.<br>
This suppresses the link about adding a comment (developers can still use the "developer" tab, to comment), if "edit" is pressed.

2024-07-31 17:26 UTC, cmb69 commented on www/bug.php
> +            If you reported this bug, you can <a href="bug.php?id=<?php echo $bug_id; ?>&amp;edit=2">edit this bug over here</a>.
This suppresses the link about adding a comment (developers can still use the "developer" tab, to comment), if "developer" is pressed.

2024-07-31 17:26 UTC, cmb69 commented on www/bug.php
> +    }
Only show "add a patch" button for developers, now.

2024-07-31 17:26 UTC, cmb69 commented on www/bug.php
> +    return false;
Nobody is allowed to vote anymore.

2024-07-31 17:26 UTC, cmb69 commented on www/patch-add.php
> +
This catches adding a patch (direct request, not UI).

2024-07-31 17:26 UTC, cmb69 commented on www/vote.php
> +die('Voting on tickets is disabled');
This catches voting.

2024-07-31 17:26 UTC, cmb69 commented on www/fix.php
> +        If you reported this bug, you can <a href="bug.php?id=<?php echo $bug_id; ?>&amp;edit=2">edit this bug over here</a>.
Not exactly sure how this can be triggered (on top of the file is a comment saying "Admin interface for closing bug reports via direct link"). I have removed the link to "add comment"; the remaining "edit" might be useful for developers who had reported a bug, and want to edit it.

2024-07-31 17:28 UTC, cmb69 commented on www/bug.php
>      $packageRepository = $container->get(PackageRepository::class);
Hmm, `$edit === 3` is no longer supposed to happen, but I've reverted this change. Shouldn't hurt.

2024-08-01 13:02 UTC, derickr commented on www/bug.php
>      $packageRepository = $container->get(PackageRepository::class);
Even with the original condition, check was for **`< 3`**, not `< 4`, so unless I misunderstood, this was already correct.

2024-08-01 13:15 UTC, derickr approved these changes
I think this looks good. Merge it?

2024-08-01 13:15 UTC, derickr commented on www/bug.php
> +        exit;
I can't really reproduce this without messing with curl on the cmd line, and I don't think it's important enough to spend a lot of time on it.

2024-08-01 13:15 UTC, derickr commented on www/bug.php
> +            If you forgot your password, <a href="bug-pwd-finder.php?id=<?php echo $bug_id; ?>">you can retrieve your password here</a>.<br>
Tested this, and is fine.

2024-08-01 13:15 UTC, derickr commented on www/bug.php
> +            If you reported this bug, you can <a href="bug.php?id=<?php echo $bug_id; ?>&amp;edit=2">edit this bug over here</a>.
Tested this, and is also fine.

2024-08-01 13:15 UTC, derickr commented on www/bug.php
> +    }
Also tested, and fine.

There is also still a link "add pull request" in the same fashion though (line 1116 below), but I guess we can leave that one?

2024-08-01 13:15 UTC, derickr commented on www/bug.php
> +    return false;
Works, cheers.

2024-08-01 13:15 UTC, derickr commented on www/fix.php
> +        If you reported this bug, you can <a href="bug.php?id=<?php echo $bug_id; ?>&amp;edit=2">edit this bug over here</a>.
+1

2024-08-01 13:15 UTC, derickr commented on www/patch-add.php
> +
I've checked that, also fine.

2024-08-01 13:15 UTC, derickr commented on www/vote.php
> +die('Voting on tickets is disabled');
And quite thoroughly :-)

2024-08-01 13:22 UTC, cmb69 commented on www/bug.php
>      $packageRepository = $container->get(PackageRepository::class);
Ah, right!

2024-08-01 13:24 UTC, cmb69 commented on www/bug.php
> +    }
This is an open issue in the OP's todo list. I think we should still allow to link PRs (they do no real harm), although that is debatable.

2024-08-01 13:28 UTC, cmb69 commented
IMO, this is good as is. The issue about linking PRs could be addressed later, if need be.

2024-08-01 13:46 UTC, merged